<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <None Update="backend\chemtrack-backend.jar">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    </ItemGroup>

    <ItemGroup>
        <None Update="frontend\dist\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </None>
    </ItemGroup>

</Project>
