<script setup>
import { computed, onMounted, reactive, ref } from 'vue'

const API = 'http://localhost:8080/api'
const active = ref('overview')
const keyword = ref('')
const apiOnline = ref(false)
const notice = ref('')
const modal = ref('')
const role = ref('LAB_ADMIN')
const dashboard = ref({ chemicalKinds: 0, lowStock: 0, expiringSoon: 0, pendingRequests: 0, openIncidents: 0, activeAlerts: 0, activeUsage: 0, pendingDisposals: 0 })
const chemicals = ref([]); const requests = ref([]); const procurements = ref([]); const usages = ref([]); const alerts = ref([]); const incidents = ref([]); const disposals = ref([]); const audit = ref([])
const form = reactive({ name:'', casNo:'', batchNo:'', hazardLevel:'中', category:'一般化学品', supplier:'', quantity:0, unit:'mL', safeThreshold:0, maxAllowedStock:0, location:'', storageRequirement:'', safetyInstructions:'', receivedAt:new Date().toISOString().slice(0,10), expiryDate:'', qrCode:'', chemicalId:'', usageId:'', applicant:'张同学', supervisor:'王老师', experiment:'', purpose:'', amount:0, actualUsed:0, returnedAmount:0, abnormalNote:'', operator:'实验室管理员', chemicalName:'', requestedBy:'实验室管理员', reason:'', estimatedCost:0, reporter:'实验室管理员', incidentType:'存储异常', severity:'一般', description:'', wasteType:'实验废液', source:'', temporaryLocation:'危废暂存间 W-01', disposalCompany:'城市环保处置中心' })

const demoChemicals = [
  { id:1,name:'浓硫酸',cas_no:'7664-93-9',batch_no:'CT-20260820-01',hazard_level:'高',category:'腐蚀品',supplier:'国药试剂',quantity:820,unit:'mL',safe_threshold:300,max_allowed_stock:2000,location:'A-01 防腐柜',storage_requirement:'阴凉、通风',expiry_date:'2027-06-30',status:'可领用' },
  { id:2,name:'无水乙醇',cas_no:'64-17-5',batch_no:'CT-20260901-02',hazard_level:'中',category:'易燃液体',supplier:'阿拉丁试剂',quantity:1250,unit:'mL',safe_threshold:500,max_allowed_stock:3000,location:'B-02 易燃柜',storage_requirement:'远离火源',expiry_date:'2026-10-18',status:'可领用' },
  { id:3,name:'过氧化氢',cas_no:'7722-84-1',batch_no:'CT-20260715-03',hazard_level:'高',category:'氧化剂',supplier:'麦克林试剂',quantity:160,unit:'mL',safe_threshold:200,max_allowed_stock:1000,location:'A-03 氧化剂柜',storage_requirement:'避光、低温',expiry_date:'2026-10-02',status:'可领用' },
  { id:4,name:'硫酸铜',cas_no:'7758-98-7',batch_no:'CT-20260512-04',hazard_level:'低',category:'一般化学品',supplier:'西陇科学',quantity:2300,unit:'g',safe_threshold:500,max_allowed_stock:5000,location:'C-04 普通试剂架',storage_requirement:'干燥密封',expiry_date:'2028-01-12',status:'可领用' }
]
const demoRequests = [
  { id:1,chemical_id:1,chemical_name:'浓硫酸',batch_no:'CT-20260820-01',hazard_level:'高',unit:'mL',applicant:'张同学',supervisor:'王老师',experiment:'材料腐蚀性测试',purpose:'耐酸性能测试',amount:50,status:'PENDING',created_at:'2026-09-11 14:18' },
  { id:2,chemical_id:3,chemical_name:'过氧化氢',batch_no:'CT-20260715-03',hazard_level:'高',unit:'mL',applicant:'李同学',supervisor:'王老师',experiment:'氧化还原反应实验',purpose:'催化剂测试',amount:30,status:'TEACHER_APPROVED',created_at:'2026-09-11 11:02' }
]

const nav = [
  ['overview','运行总览','▦'], ['chemicals','危化品档案','◫'], ['procurements','采购入库','⇩'], ['requests','领用审批','↗'], ['usages','使用归还','↻'], ['risk','风险中心','!'], ['disposals','废弃处置','♻'], ['audit','审计记录','✓']
]
const title = computed(() => nav.find(n => n[0] === active.value)?.[1] || '运行总览')
const filteredChemicals = computed(() => chemicals.value.filter(c => `${c.name} ${c.cas_no} ${c.category} ${c.batch_no}`.toLowerCase().includes(keyword.value.toLowerCase())))
const lowStock = computed(() => chemicals.value.filter(c => Number(c.quantity) <= Number(c.safe_threshold)))
const pendingRequests = computed(() => requests.value.filter(r => ['PENDING','TEACHER_APPROVED'].includes(r.status)))
const roleName = computed(() => ({ STUDENT:'学生/实验人员',TEACHER:'指导教师',LAB_ADMIN:'实验室管理员',SAFETY_OFFICER:'安全负责人',SYSTEM_ADMIN:'系统管理员' })[role.value])

async function get(path, fallback = []) { try { const r = await fetch(`${API}${path}`); if (!r.ok) throw Error(); return await r.json() } catch { return fallback } }
async function loadData() {
  const d = await get('/dashboard', null); apiOnline.value = !!d
  dashboard.value = d || { chemicalKinds:4,lowStock:1,expiringSoon:1,pendingRequests:1,openIncidents:1,activeAlerts:2,activeUsage:0,pendingDisposals:1 }
  chemicals.value = await get('/chemicals', demoChemicals); requests.value = await get('/requests', demoRequests)
  procurements.value = await get('/procurements', [{id:1,chemical_name:'丙酮',hazard_level:'中',requested_by:'实验室管理员',quantity:2000,unit:'mL',supplier:'国药试剂',estimated_cost:380,reason:'下月课程使用',status:'采购中'}])
  usages.value = await get('/usages', []); alerts.value = await get('/alerts', [{id:1,chemical_id:3,chemical_name:'过氧化氢',alert_type:'库存不足',level:'严重',title:'过氧化氢库存低于安全线',content:'当前库存 160 mL，安全线为 200 mL',status:'ACTIVE'}])
  incidents.value = await get('/incidents', [{id:1,chemical_name:'无水乙醇',reporter:'实验室管理员',incident_type:'存储异常',severity:'一般',description:'易燃柜温度短时偏高',location:'B-02 易燃柜',status:'处理中'}])
  disposals.value = await get('/disposals', [{id:1,chemical_name:'浓硫酸',amount:20,unit:'mL',waste_type:'酸性废液',source:'材料腐蚀性预实验',temporary_location:'危废暂存间 W-01',status:'待转运',applicant:'实验室管理员'}])
  audit.value = await get('/audit', [])
}
function notify(message) { notice.value = message; setTimeout(() => notice.value = '', 3000) }
function openModal(type) { modal.value = type; Object.assign(form, { name:'',casNo:'',batchNo:'',supplier:'',quantity:0,unit:'mL',safeThreshold:0,maxAllowedStock:0,location:'',storageRequirement:'',safetyInstructions:'',expiryDate:'',chemicalId:'',experiment:'',purpose:'',amount:0,chemicalName:'',reason:'',estimatedCost:0,description:'',source:'' }) }
function openReturn(u) { modal.value='return'; Object.assign(form, { usageId:u.id, actualUsed:u.issued_amount, returnedAmount:0, abnormalNote:'', operator:u.user_name || '实验室管理员' }) }
function closeModal() { modal.value = '' }
async function post(path, body) { const r = await fetch(`${API}${path}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) }); if (!r.ok) throw Error((await r.json().catch(() => ({}))).message || '操作失败'); return r.json() }
async function submit() {
  try {
    if (modal.value === 'chemical') await post('/chemicals', { name:form.name,casNo:form.casNo,batchNo:form.batchNo,hazardLevel:form.hazardLevel,category:form.category,supplier:form.supplier,quantity:Number(form.quantity),unit:form.unit,safeThreshold:Number(form.safeThreshold),maxAllowedStock:Number(form.maxAllowedStock),location:form.location,storageRequirement:form.storageRequirement,safetyInstructions:form.safetyInstructions,receivedAt:form.receivedAt,expiryDate:form.expiryDate,qrCode:form.qrCode })
    if (modal.value === 'procurement') await post('/procurements', { chemicalName:form.chemicalName,casNo:form.casNo,hazardLevel:form.hazardLevel,requestedBy:form.requestedBy,quantity:Number(form.quantity),unit:form.unit,supplier:form.supplier,estimatedCost:Number(form.estimatedCost),reason:form.reason })
    if (modal.value === 'request') await post('/requests', { chemicalId:Number(form.chemicalId),applicant:form.applicant,supervisor:form.supervisor,experiment:form.experiment,purpose:form.purpose,amount:Number(form.amount) })
    if (modal.value === 'incident') await post('/incidents', { chemicalId:form.chemicalId ? Number(form.chemicalId) : null,reporter:form.reporter,incidentType:form.incidentType,severity:form.severity,description:form.description,location:form.location })
    if (modal.value === 'disposal') await post('/disposals', { chemicalId:Number(form.chemicalId),source:form.source,amount:Number(form.amount),unit:form.unit,wasteType:form.wasteType,temporaryLocation:form.temporaryLocation,disposalCompany:form.disposalCompany,applicant:form.applicant })
    if (modal.value === 'return') { const r = await fetch(`${API}/usages/${form.usageId}/return`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ actualUsed:Number(form.actualUsed), returnedAmount:Number(form.returnedAmount), abnormalNote:form.abnormalNote, operator:form.operator }) }); if (!r.ok) throw Error((await r.json().catch(()=>({}))).message || '归还登记失败') }
    closeModal(); notify('操作成功，记录已写入审计日志'); await loadData()
  } catch (e) { notify(e.message || '演示模式：操作已记录在当前页面') }
}
async function patch(path, params = {}) { const qs = new URLSearchParams(params).toString(); const r = await fetch(`${API}${path}${qs ? '?' + qs : ''}`, { method:'PATCH' }); if (!r.ok) throw Error(); return r.json() }
async function decide(r) { try { const stage = r.status === 'TEACHER_APPROVED' ? 'admin' : 'teacher'; await patch(`/requests/${r.id}/approve`, { stage, approver:stage === 'admin' ? '实验室管理员' : '王老师' }); notify(stage === 'admin' ? '管理员复核完成，可办理发放' : (r.hazard_level === '高' ? '教师审批完成，等待管理员复核' : '审批通过')); await loadData() } catch { r.status = r.status === 'PENDING' && r.hazard_level === '高' ? 'TEACHER_APPROVED' : 'APPROVED'; notify('演示模式：审批状态已更新') } }
async function reject(r) { try { await patch(`/requests/${r.id}/reject`); notify('申请已驳回'); await loadData() } catch { r.status = 'REJECTED'; notify('演示模式：申请已驳回') } }
async function issue(r) { try { await patch(`/requests/${r.id}/issue`, { amount:r.amount }); notify('已完成出库，使用归还记录已建立'); await loadData() } catch { notify('请确认后端已升级并完成数据库脚本') } }
async function advanceProcurement(p) { const flow = ['待审批','采购中','待验收','已入库']; const next = flow[Math.min(flow.indexOf(p.status)+1,3)]; try { await patch(`/procurements/${p.id}/advance`, { status:next }); notify('采购流程已推进至 ' + next); await loadData() } catch { p.status = next; notify('演示模式：采购流程已推进') } }
async function refreshAlerts() { try { await post('/alerts/refresh', {}); notify('已完成库存、有效期预警扫描'); await loadData() } catch { notify('演示模式：预警扫描完成') } }
async function resolveAlert(a) { try { await patch(`/alerts/${a.id}/resolve`); notify('预警已关闭'); await loadData() } catch { a.status='RESOLVED'; notify('演示模式：预警已关闭') } }
async function handleIncident(i) { const next = i.status === '待处理' ? '处理中' : '已关闭'; try { await patch(`/incidents/${i.id}/handle`, { status:next }); notify('异常状态已更新'); await loadData() } catch { i.status=next; notify('演示模式：异常状态已更新') } }
async function advanceDisposal(d) { const flow=['待申请','待转运','处理中','已处置']; const next=flow[Math.min(flow.indexOf(d.status)+1,3)]; try { await patch(`/disposals/${d.id}/advance`,{status:next}); notify('处置流程已推进至 '+next); await loadData() } catch { d.status=next; notify('演示模式：处置流程已推进') } }
function statusLabel(s) { return ({PENDING:'待审批',TEACHER_APPROVED:'待管理员复核',APPROVED:'待发放',REJECTED:'已驳回',ISSUED:'使用中',RETURNED:'已归还',ABNORMAL:'异常'})[s] || s }
function riskClass(s) { return s === '高' ? 'high' : s === '中' ? 'medium' : 'low' }
onMounted(loadData)
</script>

<template>
  <div class="app-shell">
    <aside class="sidebar"><div class="brand"><img class="brand-mark" src="/chemtrack-avatar.jpg" alt="ChemTrack 图标"/><div><strong>ChemTrack</strong><small>危化品全生命周期</small></div></div>
      <nav><button v-for="n in nav" :key="n[0]" :class="{active:active===n[0]}" @click="active=n[0]"><span>{{ n[2] }}</span>{{ n[1] }}<i v-if="n[0]==='requests' && dashboard.pendingRequests">{{ dashboard.pendingRequests }}</i><i v-if="n[0]==='risk' && dashboard.activeAlerts">{{ dashboard.activeAlerts }}</i></button></nav>
      <div class="sidebar-foot"><span class="dot" :class="{offline:!apiOnline}"></span>{{ apiOnline ? '后端已连接' : '演示数据模式' }}<small>{{ roleName }} · 实验中心</small></div>
    </aside>
    <main class="main"><header class="topbar"><div><p class="eyebrow">实验中心 / 安全管理</p><Transition name="title" mode="out-in"><h1 :key="title">{{ title }}</h1></Transition></div><div class="top-actions"><span class="date">2026年9月12日</span><select v-model="role" aria-label="切换演示角色"><option value="LAB_ADMIN">管理员</option><option value="TEACHER">指导教师</option><option value="STUDENT">学生</option><option value="SAFETY_OFFICER">安全负责人</option></select><button class="avatar">管</button></div></header>
      <Transition name="toast"><div v-if="notice" class="toast">{{ notice }}</div></Transition>
      <Transition name="page" mode="out-in">
      <section v-if="active==='overview'" key="overview" class="content"><div class="hero-line"><div><h2>今天的实验室状态</h2><p>采购、库存、领用、使用、处置和异常都在同一条责任链上。</p></div><button class="primary" @click="active='requests'">处理待办 <span>→</span></button></div>
        <div class="metrics"><article><span>危化品批次</span><strong>{{ dashboard.chemicalKinds }}</strong><small>已建档可追溯</small></article><article class="amber"><span>库存预警</span><strong>{{ dashboard.lowStock }}</strong><small>低于安全线</small></article><article class="coral"><span>30天内到期</span><strong>{{ dashboard.expiringSoon }}</strong><small>需要优先处置</small></article><article class="teal"><span>待审批申请</span><strong>{{ dashboard.pendingRequests }}</strong><small>高风险需双重确认</small></article><article class="violet"><span>开放异常</span><strong>{{ dashboard.openIncidents }}</strong><small>等待安全负责人</small></article><article class="blue"><span>使用中</span><strong>{{ dashboard.activeUsage }}</strong><small>尚未归还</small></article><article class="rose"><span>有效预警</span><strong>{{ dashboard.activeAlerts }}</strong><small>建议今日处理</small></article><article class="amber"><span>待处置</span><strong>{{ dashboard.pendingDisposals }}</strong><small>危废流程</small></article></div>
        <div class="split"><section class="panel"><div class="panel-head"><div><h3>风险雷达</h3><p>系统自动识别库存、有效期与存储异常</p></div><button class="text-btn" @click="active='risk'">查看全部 →</button></div><div v-for="a in alerts.slice(0,3)" :key="a.id" class="alert-row"><div class="alert-icon">!</div><div class="alert-copy"><strong>{{ a.title }}</strong><span>{{ a.content }}</span></div><span class="tag" :class="a.level==='严重'?'danger':'warn'">{{ a.level }}</span></div><div v-if="!alerts.length" class="empty">当前没有有效预警</div></section><section class="panel"><div class="panel-head"><div><h3>最近申请</h3><p>审批与发放状态一目了然</p></div><button class="text-btn" @click="active='requests'">进入审批 →</button></div><div v-for="r in requests.slice(0,3)" :key="r.id" class="request-mini"><div><strong>{{ r.chemical_name }}</strong><span>{{ r.applicant }} · {{ r.experiment }}</span></div><span class="tag" :class="r.status==='PENDING'||r.status==='TEACHER_APPROVED'?'warn':r.status==='REJECTED'?'danger':'ok'">{{ statusLabel(r.status) }}</span></div></section></div>
        <section class="panel process"><div class="panel-head"><div><h3>全生命周期</h3><p>每个批次都留下证据链，适合课堂演示和审计追溯</p></div></div><div class="steps"><div class="step done"><b>01</b><span>采购申请</span></div><div class="connector done"></div><div class="step done"><b>02</b><span>到货验收</span></div><div class="connector done"></div><div class="step current"><b>03</b><span>领用审批</span></div><div class="connector"></div><div class="step"><b>04</b><span>使用归还</span></div><div class="connector"></div><div class="step"><b>05</b><span>废弃处置</span></div></div></section>
      </section>

      <section v-else-if="active==='chemicals'" key="chemicals" class="content"><div class="toolbar"><div><h2>危化品档案</h2><p>按名称、CAS、批次或分类查找，支持存储要求和二维码标识</p></div><div class="toolbar-actions"><input v-model="keyword" placeholder="搜索档案"/><button class="primary" @click="openModal('chemical')">＋ 新增档案</button></div></div><section class="panel table-panel"><table><thead><tr><th>名称 / CAS / 批次</th><th>风险</th><th>供应商</th><th>库存 / 安全线</th><th>位置 / 存储要求</th><th>有效期</th><th>状态</th></tr></thead><tbody><tr v-for="c in filteredChemicals" :key="c.id"><td><strong>{{ c.name }}</strong><small>{{ c.cas_no }} · {{ c.batch_no }}</small></td><td><span class="risk" :class="riskClass(c.hazard_level)">{{ c.hazard_level }}</span></td><td>{{ c.supplier }}</td><td><strong :class="Number(c.quantity)<=Number(c.safe_threshold)?'text-danger':''">{{ c.quantity }} {{ c.unit }}</strong><small>安全线 {{ c.safe_threshold }} {{ c.unit }}</small></td><td>{{ c.location }}<small>{{ c.storage_requirement }}</small></td><td>{{ c.expiry_date }}</td><td><span class="tag" :class="c.status==='可领用'?'ok':'warn'">{{ c.status }}</span></td></tr></tbody></table></section></section>

      <section v-else-if="active==='procurements'" key="procurements" class="content"><div class="toolbar"><div><h2>采购与入库</h2><p>采购申请 → 审批 → 到货验收 → 入库完成</p></div><button class="primary" @click="openModal('procurement')">＋ 新建采购申请</button></div><section class="panel table-panel"><table><thead><tr><th>物料</th><th>申请人 / 原因</th><th>数量</th><th>供应商 / 预算</th><th>状态</th><th>流程操作</th></tr></thead><tbody><tr v-for="p in procurements" :key="p.id"><td><strong>{{ p.chemical_name }}</strong><small>{{ p.cas_no }} · {{ p.hazard_level }}风险</small></td><td>{{ p.requested_by }}<small>{{ p.reason }}</small></td><td>{{ p.quantity }} {{ p.unit }}</td><td>{{ p.supplier || '待定' }}<small>¥ {{ p.estimated_cost || 0 }}</small></td><td><span class="tag" :class="p.status==='已入库'?'ok':p.status==='已驳回'?'danger':'warn'">{{ p.status }}</span></td><td><button v-if="p.status!=='已入库'&&p.status!=='已驳回'" class="small-btn" @click="advanceProcurement(p)">推进流程 →</button><span v-else class="muted">流程完成</span></td></tr></tbody></table></section></section>

      <section v-else-if="active==='requests'" key="requests" class="content"><div class="toolbar"><div><h2>领用审批</h2><p>高风险试剂必须经过指导教师与管理员双重审批</p></div><button class="primary" @click="openModal('request')">＋ 新建领用申请</button></div><section class="panel table-panel"><table><thead><tr><th>申请人 / 实验</th><th>危化品 / 批次</th><th>申请量</th><th>状态</th><th>审批与发放</th></tr></thead><tbody><tr v-for="r in requests" :key="r.id"><td><strong>{{ r.applicant }}</strong><small>{{ r.experiment }} · {{ r.purpose }}</small></td><td><strong>{{ r.chemical_name }}</strong><small>{{ r.batch_no }} · <span class="risk" :class="riskClass(r.hazard_level)">{{ r.hazard_level }}风险</span></small></td><td>{{ r.amount }} {{ r.unit }}</td><td><span class="tag" :class="r.status==='REJECTED'?'danger':r.status==='APPROVED'||r.status==='ISSUED'||r.status==='RETURNED'?'ok':'warn'">{{ statusLabel(r.status) }}</span></td><td><div v-if="r.status==='PENDING'||r.status==='TEACHER_APPROVED'" class="row-actions"><button class="approve" @click="decide(r)">{{ r.status==='TEACHER_APPROVED'?'管理员复核':'审批' }}</button><button class="reject" @click="reject(r)">驳回</button></div><button v-else-if="r.status==='APPROVED'" class="small-btn" @click="issue(r)">办理发放</button><span v-else class="muted">已进入生命周期</span></td></tr></tbody></table></section></section>

      <section v-else-if="active==='usages'" key="usages" class="content"><div class="toolbar"><div><h2>使用与归还</h2><p>记录实际使用量、剩余量和异常说明，归还量自动回补库存</p></div></div><section class="panel table-panel"><table><thead><tr><th>领用人 / 实验</th><th>危化品 / 批次</th><th>发放量</th><th>实际使用</th><th>归还量</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="u in usages" :key="u.id"><td><strong>{{ u.user_name }}</strong><small>{{ u.experiment }}</small></td><td>{{ u.chemical_name }}<small>{{ u.batch_no }}</small></td><td>{{ u.issued_amount }}</td><td>{{ u.actual_used ?? '—' }}</td><td>{{ u.returned_amount ?? '—' }}</td><td><span class="tag" :class="u.status==='异常'?'danger':u.status==='已归还'?'ok':'warn'">{{ u.status }}</span></td><td><button v-if="u.status!=='已归还'" class="small-btn" @click="openReturn(u)">登记归还</button><span v-else class="muted">已完成</span></td></tr><tr v-if="!usages.length"><td colspan="7" class="empty">暂无使用记录，审批通过后办理发放即可进入此处。</td></tr></tbody></table></section></section>

      <section v-else-if="active==='risk'" key="risk" class="content"><div class="toolbar"><div><h2>风险中心</h2><p>预警、异常和处置动作统一闭环</p></div><button class="primary" @click="refreshAlerts">↻ 立即扫描预警</button></div><div class="split"><section class="panel"><div class="panel-head"><div><h3>有效预警</h3><p>库存、有效期和规则预警</p></div></div><div v-for="a in alerts" :key="a.id" class="alert-row"><div class="alert-icon">!</div><div class="alert-copy"><strong>{{ a.title }}</strong><span>{{ a.content }}</span></div><span class="tag" :class="a.level==='严重'?'danger':'warn'">{{ a.level }}</span><button class="small-btn" @click="resolveAlert(a)">关闭</button></div><div v-if="!alerts.length" class="empty">暂无有效预警</div></section><section class="panel"><div class="panel-head"><div><h3>异常上报</h3><p>泄漏、存储异常和数量异常必须留痕</p></div><button class="text-btn" @click="openModal('incident')">＋ 上报异常</button></div><div v-for="i in incidents" :key="i.id" class="incident-row"><div><strong>{{ i.incident_type }} · {{ i.chemical_name || '未关联试剂' }}</strong><span>{{ i.description }} · {{ i.location }}</span></div><span class="tag" :class="i.severity==='重大'?'danger':'warn'">{{ i.status }}</span><button class="small-btn" @click="handleIncident(i)">{{ i.status==='已关闭'?'已关闭':'推进处理' }}</button></div></section></div></section>

      <section v-else-if="active==='disposals'" key="disposals" class="content"><div class="toolbar"><div><h2>废弃物处置</h2><p>申请、暂存、转运和最终处置全程留痕</p></div><button class="primary" @click="openModal('disposal')">＋ 登记处置申请</button></div><section class="panel table-panel"><table><thead><tr><th>来源 / 废物类型</th><th>危化品</th><th>数量</th><th>暂存位置 / 处置单位</th><th>状态</th><th>流程操作</th></tr></thead><tbody><tr v-for="d in disposals" :key="d.id"><td><strong>{{ d.source }}</strong><small>{{ d.waste_type }} · {{ d.applicant }}</small></td><td>{{ d.chemical_name }}<small>{{ d.batch_no }}</small></td><td>{{ d.amount }} {{ d.unit }}</td><td>{{ d.temporary_location }}<small>{{ d.disposal_company }}</small></td><td><span class="tag" :class="d.status==='已处置'?'ok':'warn'">{{ d.status }}</span></td><td><button v-if="d.status!=='已处置'" class="small-btn" @click="advanceDisposal(d)">推进流程 →</button><span v-else class="muted">已归档</span></td></tr></tbody></table></section></section>

      <section v-else key="audit" class="content"><div class="hero-line"><div><h2>审计记录</h2><p>关键操作不可删除，保留操作人、角色、时间、对象和结果。</p></div></div><section class="panel audit-list"><div v-for="a in audit" :key="a.id" class="audit-item"><span class="audit-time">{{ String(a.created_at || '').slice(11,16) }}</span><b>{{ a.action }}</b><span>{{ a.operator_name }} · {{ a.detail }}</span><em :class="a.result==='SUCCESS'?'success':''">{{ a.result==='SUCCESS'?'已完成':'失败' }}</em></div><div v-if="!audit.length" class="empty">暂无审计记录</div></section></section>
      </Transition>
    </main>
    <div v-if="modal" class="modal-backdrop" @click.self="closeModal"><form class="modal-card" @submit.prevent="submit"><button type="button" class="modal-close" @click="closeModal">×</button><h3>{{ modal==='chemical'?'新增危化品档案':modal==='procurement'?'新建采购申请':modal==='request'?'新建领用申请':modal==='incident'?'上报实验室异常':'登记废弃物处置' }}</h3>
      <div v-if="modal==='chemical'" class="form-grid"><label>名称<input v-model="form.name" required/></label><label>CAS 编号<input v-model="form.casNo" required/></label><label>批次号<input v-model="form.batchNo" required/></label><label>风险等级<select v-model="form.hazardLevel"><option>高</option><option>中</option><option>低</option></select></label><label>分类<input v-model="form.category" required/></label><label>供应商<input v-model="form.supplier" required/></label><label>数量<input v-model.number="form.quantity" type="number" min="0" required/></label><label>单位<input v-model="form.unit" required/></label><label>安全线<input v-model.number="form.safeThreshold" type="number" min="0" required/></label><label>存放位置<input v-model="form.location" required/></label><label>入库日期<input v-model="form.receivedAt" type="date" required/></label><label>有效期<input v-model="form.expiryDate" type="date" required/></label><label class="wide">存储要求<input v-model="form.storageRequirement"/></label></div>
      <div v-else-if="modal==='procurement'" class="form-grid"><label>物料名称<input v-model="form.chemicalName" required/></label><label>CAS 编号<input v-model="form.casNo"/></label><label>风险等级<select v-model="form.hazardLevel"><option>高</option><option>中</option><option>低</option></select></label><label>数量<input v-model.number="form.quantity" type="number" min="0.01" required/></label><label>单位<input v-model="form.unit" required/></label><label>供应商<input v-model="form.supplier"/></label><label>预算<input v-model.number="form.estimatedCost" type="number" min="0"/></label><label class="wide">采购理由<textarea v-model="form.reason" required/></label></div>
      <div v-else-if="modal==='request'" class="form-grid"><label>选择批次<select v-model="form.chemicalId" required><option value="" disabled>请选择</option><option v-for="c in chemicals" :key="c.id" :value="c.id">{{ c.name }} · {{ c.batch_no }} · 库存 {{ c.quantity }}{{ c.unit }}</option></select></label><label>申请人<input v-model="form.applicant" required/></label><label>指导教师<input v-model="form.supervisor" required/></label><label>申请数量<input v-model.number="form.amount" type="number" min="0.01" required/></label><label class="wide">实验名称<input v-model="form.experiment" required/></label><label class="wide">用途说明<textarea v-model="form.purpose" required/></label></div>
      <div v-else-if="modal==='incident'" class="form-grid"><label>关联批次<select v-model="form.chemicalId"><option value="">暂不关联</option><option v-for="c in chemicals" :key="c.id" :value="c.id">{{ c.name }} · {{ c.batch_no }}</option></select></label><label>上报人<input v-model="form.reporter" required/></label><label>类型<select v-model="form.incidentType"><option>泄漏</option><option>包装破损</option><option>存储异常</option><option>人员暴露</option><option>数量异常</option><option>其他</option></select></label><label>严重程度<select v-model="form.severity"><option>一般</option><option>较大</option><option>重大</option></select></label><label class="wide">地点<input v-model="form.location"/></label><label class="wide">情况描述<textarea v-model="form.description" required/></label></div>
      <div v-else-if="modal==='disposal'" class="form-grid"><label>选择批次<select v-model="form.chemicalId" required><option value="" disabled>请选择</option><option v-for="c in chemicals" :key="c.id" :value="c.id">{{ c.name }} · {{ c.batch_no }}</option></select></label><label>申请人<input v-model="form.applicant" required/></label><label>废物类型<input v-model="form.wasteType" required/></label><label>数量<input v-model.number="form.amount" type="number" min="0.01" required/></label><label>单位<input v-model="form.unit" required/></label><label>来源<input v-model="form.source" required/></label><label>暂存位置<input v-model="form.temporaryLocation" required/></label><label>处置单位<input v-model="form.disposalCompany"/></label></div>
      <div v-else class="form-grid"><label>实际使用量<input v-model.number="form.actualUsed" type="number" min="0" required/></label><label>归还量<input v-model.number="form.returnedAmount" type="number" min="0" required/></label><label>登记人<input v-model="form.operator" required/></label><label class="wide">异常说明<textarea v-model="form.abnormalNote" placeholder="无异常可留空"></textarea></label></div>
      <div class="modal-actions"><button type="button" class="ghost" @click="closeModal">取消</button><button class="primary" type="submit">保存并写入审计</button></div>
    </form></div>
  </div>
</template>
